sylius_adyen_admin_log:
    resource: |
        alias: sylius_adyen.log
        section: admin
        path: /adyen/log
        permission: true
        templates: "@SyliusAdmin\\Crud"
        redirect: update
        grid: sylius_adyen_admin_log
        vars:
            all:
                hook_prefix: 'sylius_adyen.admin.log'
    type: sylius.resource

sylius_adyen_admin_order_payment_generate_pay_link:
    path: /adyen/payment/{id}/generate-pay-link
    methods: [GET]
    controller: sylius_adyen.controller.admin.payment.generate_pay_link

sylius_adyen_admin_order_payment_reverse:
    path: /order/{id}/payments/{paymentId}/reverse
    methods: [GET]
    controller: sylius_adyen.controller.admin.order_payment.reverse

sylius_adyen_admin_order_payment_capture:
    path: /order/{id}/payments/{paymentId}/capture
    methods: [PUT]
    controller: sylius_adyen.controller.admin.order_payment.capture
