imports:
    - { resource: "@SyliusAdyenPlugin/config/grids/*/*.yaml" }
    - { resource: "@SyliusAdyenPlugin/config/sylius/blocks.yml" }
    - { resource: "@SyliusAdyenPlugin/config/sylius/resources.yml" }
    - { resource: "@SyliusAdyenPlugin/config/winzou_state_machine/**.yaml" }
    - { resource: "@SyliusAdyenPlugin/config/workflow/**.yaml" }
    - { resource: "@SyliusAdyenPlugin/config/sylius_adyen.yaml" }

parameters:
    sylius_adyen_api_platform_mapping_path: '%kernel.project_dir%/vendor/sylius/adyen-plugin/config/api_resources/'

api_platform:
    mapping:
        paths:
            - '%sylius_adyen_api_platform_mapping_path%'

sylius_mailer:
    emails:
        adyen_payment_link:
            subject: Payment link
            template: "@SyliusAdyenPlugin/Shop/Email/paymentLink.html.twig"
