winzou_state_machine:
    sylius_payment:
        states:
            processing_reversal: ~
        transitions:
            capture:
                from: [new, processing, authorized]
                to: completed
            process:
                from: [new, authorized]
                to: processing
            cancel:
                from: [new, processing, authorized, processing_reversal]
                to: cancelled
            refund:
                from: [completed, processing_reversal]
                to: refunded
            reverse:
                from: [completed]
                to: processing_reversal
        callbacks:
            after:
                sylius_resolve_state:
                    on: ["complete", "process", "refund", "authorize", "capture"]
                auto_capture:
                    on: ["authorize"]
                    do: ["@sylius_adyen.processor.authorization_state", "process"]
                    args: ["object"]
                    priority: 100
                process_order_payment_after_reversal:
                    on: ["cancel", "refund"]
                    do: ["@sylius_adyen.processor.order.update_order_payment_state", "process"]
                    args: ["object.getOrder()"]
            guard:
                guard_manual_complete:
                    on: ["complete"]
                    do: ["@sylius_adyen.state_machine.guard.payment", "canBeCompleted"]
                    args: ["object"]
                guard_manual_cancel:
                    on: ["cancel"]
                    do: ["@sylius_adyen.state_machine.guard.payment", "canBeCancelled"]
                    args: ["object"]
